## GitHub Action to perform the following steps
## build the project
## call the maven-dependency-submission-action

name: Build and Submit

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'
# print the current directory and the files in it
            - name: Print current directory
              run: pwd | ls -l
 #           - name: Build with Maven
 #             run: mvn -B package --file parent-project/pom.xml
            - name: Maven Dependency Tree Dependency Submission
              uses: advanced-security/maven-dependency-submission-action@v3.0.2



    

